import os
import httpx
from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any

router = APIRouter()

ENFORCER = os.getenv("POLICY_ENFORCER_URL", "http://policy_enforcer:8181").rstrip("/")

@router.get("/decision-logs")
async def decision_logs():
    """Fetch and transform OPA decision log events from the policy enforcer.

    This endpoint proxies the decision log events stored by the
    ``policy_enforcer`` service and adapts them for display in the
    Open WebUI.  Each log entry returned contains the following keys:

    * ``result`` – ``"allow"`` or ``"block"``, derived from the OPA
      ``result`` field
    * ``user_email`` – email address provided in the input (if any)
    * ``phase`` – the phase from the guard decision input (if any)
    * ``timestamp`` – RFC3339 timestamp of the decision
    * ``decision_id`` – the unique decision identifier generated by OPA
    * ``raw`` – the full, original decision log event from OPA
    """
    url = f"{ENFORCER}/decision_logs"
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            r = await client.get(url, headers={"accept": "application/json"})
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to reach policy enforcer: {e}")
    if r.status_code != 200:
        raise HTTPException(status_code=r.status_code, detail=r.text)
    try:
        data = r.json()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to parse JSON from policy enforcer: {exc}")
    items = data if isinstance(data, list) else [data]
    # Drop null/empty events
    events = [x for x in items if isinstance(x, dict) and x]
    mapped = []  # type: List[Dict[str, Any]]
    for ev in events:
        # Derive allow/block from the OPA result.  OPA may encode
        # booleans as strings or actual booleans.  Treat truthy values
        # ("true", True) as allow.
        raw_result = ev.get("result")
        is_allow = False
        if isinstance(raw_result, bool):
            is_allow = raw_result
        elif isinstance(raw_result, str):
            is_allow = raw_result.lower() == "true"
        result_str = "allow" if is_allow else "block"
        # Extract user_email and phase from the input if present
        input_obj = ev.get("input") or {}
        user_email = input_obj.get("user_email")
        phase = input_obj.get("phase")
        mapped.append({
            "result": result_str,
            "user_email": user_email,
            "phase": phase,
            "timestamp": ev.get("timestamp"),
            "decision_id": ev.get("decision_id"),
            # Include the full event as ``raw`` for detailed inspection
            "raw": ev,
        })
    return mapped
