import os
import re
import httpx
import redis
from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any, Optional

router = APIRouter()

ENFORCER = os.getenv("POLICY_ENFORCER_URL", "http://policy_enforcer:8181").rstrip("/")

# Base URL for the MAD parser service.  The policies tab in the web UI
# relies on the rego policies stored by the MAD parser sidecar.  Each
# department policy can be retrieved via GET /rego_policy/<department>.
MAD_PARSER = os.getenv("MAD_PARSER_URL", "http://mad_parser:7777").rstrip("/")

# Redis connection URL.  The MAD parser and policy enforcer share a
# common Valkey instance for storing group and policy mappings.  We
# inspect the rego_policy:* keys to enumerate available department
# policies for the new policies tab.  Use decode_responses so values
# are returned as Python strings.
REDIS_URL = os.getenv("REDIS_URL", "redis://valkey:6379/0")

# Base URL for the orchestrator service.  The action settings tab in
# the Web UI proxies configuration to the orchestrator via these
# endpoints.  The URL should point to the root of the orchestrator
# API where the ``/config`` endpoints live.  Defaults to the
# orchestrator service deployed in Docker.
ORCHESTRATOR = os.getenv(
    "ORCHESTRATOR_URL",
    "http://orchestrator:8000/promptsage/orchestrator/v1",
).rstrip("/")

@router.get("/decision-logs")
async def decision_logs():
    """Fetch and transform OPA decision log events from the policy enforcer.

    This endpoint proxies the decision log events stored by the
    ``policy_enforcer`` service and adapts them for display in the
    Open WebUI.  Each log entry returned contains the following keys:

    * ``result`` – ``"allow"``, ``"warn"`` or ``"block"``.  The value
      reflects the action taken by the orchestrator after applying the
      current action settings.  A ``warn`` indicates the request was
      allowed but a warning action was present in the policy decision.
      A ``block`` indicates the request was blocked.  ``allow`` means
      the request was allowed and no warning applies.
    * ``recommended_action`` – suggested remediation action from the
      decision, if provided by the policy (otherwise ``None``)
    * ``user_email`` – email address provided in the input (if any)
    * ``phase`` – the phase from the guard decision input (if any)
    * ``timestamp`` – RFC3339 timestamp of the decision
    * ``decision_id`` – the unique decision identifier generated by OPA
    * ``summary`` – a human readable summary explaining why a
      decision was blocked (only present when result is ``"block"``)
    * ``raw`` – the full, original decision log event from the enforcer
    """
    url = f"{ENFORCER}/decision_logs"
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            r = await client.get(url, headers={"accept": "application/json"})
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to reach policy enforcer: {e}")
    if r.status_code != 200:
        raise HTTPException(status_code=r.status_code, detail=r.text)
    try:
        data = r.json()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to parse JSON from policy enforcer: {exc}")
    items = data if isinstance(data, list) else [data]
    # Drop null/empty events
    events = [x for x in items if isinstance(x, dict) and x]
    # Fetch the current orchestrator configuration to compute the final
    # allow/block result.  If the orchestrator cannot be reached or
    # parsing fails, fall back to default values (block on "block"
    # actions and honour the boolean allow flag).
    decision_block_level = "block"
    allow_fallback_block = True
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            cfg_resp = await client.get(
                f"{ORCHESTRATOR}/config", headers={"accept": "application/json"}
            )
        if cfg_resp.status_code == 200:
            cfg = cfg_resp.json()
            if isinstance(cfg.get("decision_block_level"), str):
                level = cfg["decision_block_level"].lower()
                if level in {"none", "warn", "block"}:
                    decision_block_level = level
            if isinstance(cfg.get("allow_fallback_block"), bool):
                allow_fallback_block = cfg["allow_fallback_block"]
    except Exception:
        # ignore errors and use defaults
        pass
    mapped: List[Dict[str, Any]] = []
    for ev in events:
        # Determine the decision details.  The policy enforcer stores
        # structured decisions under the "decision" key for local logs.  OPA
        # events record the evaluation result under "result".  Fall back
        # to the top-level "allow" key when present.
        decision_obj: Optional[Dict[str, Any]] = None
        raw_result = ev.get("result")
        if isinstance(ev.get("decision"), dict):
            decision_obj = ev.get("decision")
        elif isinstance(raw_result, dict):
            decision_obj = raw_result
        # Determine the boolean allow flag (legacy allow).  This will
        # be used when no structured action is present.
        allow_bool: Optional[bool] = None
        if decision_obj is not None:
            if "allow" in decision_obj:
                allow_bool = bool(decision_obj.get("allow"))
            else:
                # Fallback: treat truthiness of decision object as allow
                allow_bool = bool(decision_obj)
        elif isinstance(raw_result, bool):
            allow_bool = raw_result
        elif isinstance(raw_result, str):
            allow_bool = raw_result.lower() == "true"
        elif isinstance(ev.get("allow"), bool):
            allow_bool = ev.get("allow")
        else:
            # Default to False when unable to determine
            allow_bool = False
        # Determine decision action (if present)
        decision_action: Optional[str] = None
        if isinstance(decision_obj, dict):
            act = decision_obj.get("action")
            if isinstance(act, str):
                decision_action = act
        # Compute final allow based on orchestrator configuration
        if decision_action is not None:
            act_l = decision_action.lower()
            if decision_block_level == "none":
                final_allow = True
            elif decision_block_level == "warn":
                final_allow = act_l not in {"warn", "block"}
            else:  # "block"
                final_allow = act_l != "block"
        else:
            if allow_fallback_block:
                final_allow = bool(allow_bool)
            else:
                final_allow = True
        # Determine the result string based on the final outcome and
        # decision action.  When the action settings are disabled
        # (decision_block_level == "none"), always report "allow".
        # Otherwise, report "warn" when the request is allowed and the
        # original decision action was "warn".  Report "block" when
        # the request is blocked.  In all other allowed cases, report
        # "allow".
        if decision_block_level == "none":
            # Disabled behaviour: ignore decision_action entirely
            result_str = "allow"
        else:
            if not final_allow:
                result_str = "block"
            else:
                if decision_action is not None and decision_action.lower() == "warn":
                    result_str = "warn"
                else:
                    result_str = "allow"
        # Extract recommended action from the decision if present
        recommended_action: Optional[Any] = None
        if isinstance(decision_obj, dict):
            recommended_action = decision_obj.get("action")
        # Extract reasons for summary if present
        reasons = None
        if isinstance(decision_obj, dict) and "reasons" in decision_obj:
            reasons = decision_obj.get("reasons")
        # Extract user_email, phase and evaluated_policy from the input if present
        input_obj = ev.get("input") or {}
        user_email = input_obj.get("user_email")
        phase = input_obj.get("phase")
        evaluated_policy = input_obj.get("evaluated_policy")
        # Compute a human-readable summary when blocked and sufficient info is available
        summary: Optional[str] = None
        if not final_allow and phase and evaluated_policy and reasons:
            # Convert reasons to a comma-separated string
            if isinstance(reasons, list):
                reasons_str = ", ".join(str(x) for x in reasons)
            else:
                reasons_str = str(reasons)
            summary = (
                f"The {phase} phase content violated the {evaluated_policy} "
                f"policy from triggering the {reasons_str} guardrail rules."
            )
        mapped.append({
            "result": result_str,
            "recommended_action": recommended_action,
            "user_email": user_email,
            "phase": phase,
            "timestamp": ev.get("timestamp"),
            "decision_id": ev.get("decision_id"),
            "summary": summary,
            # Include the full event as ``raw`` for detailed inspection
            "raw": ev,
        })
    return mapped


@router.get("/policies")
async def list_policies() -> List[Dict[str, Any]]:
    """
    Return a list of department rego policies for display in the audit UI.

    The MAD parser stores per‑department policies in Valkey under keys
    formatted as ``rego_policy:<department>``.  Group‑level assignments
    also use the same prefix but include GUIDs in place of a
    department name.  To build the policies tab we enumerate all
    ``rego_policy:*`` keys, filter out values that appear to be
    department names (e.g. all lowercase letters and underscores), and
    then fetch each policy's contents via the MAD parser REST API.

    Each returned object has the following fields:

    * ``name`` – the department name (e.g. ``"business"``)
    * ``policy`` – the full Rego policy text for that department

    If a policy cannot be retrieved or parsed, it is skipped.  An
    empty list is returned when no department policies are found.
    """
    # Connect to Valkey/Redis to list policy keys.  We do this
    # synchronously since the redis client is not async.  Use a small
    # scan count to avoid blocking the event loop for too long.
    try:
        r = redis.Redis.from_url(REDIS_URL, decode_responses=True)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to connect to Redis: {exc}")
    try:
        keys = list(r.scan_iter(match="rego_policy:*", count=1000))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to scan policy keys: {exc}")
    # Extract candidate department names from keys.  A department
    # name is assumed to consist of lowercase letters and underscores
    # only.  This heuristic avoids selecting group IDs (GUIDs) which
    # contain digits and hyphens.
    depts = []
    for key in keys:
        # Key format: rego_policy:<name>
        parts = key.split(":", 1)
        if len(parts) != 2:
            continue
        name = parts[1]
        if re.fullmatch(r"[a-z_]+", name):
            depts.append(name)
    # Deduplicate and sort for stable output
    depts = sorted(set(depts))
    if not depts:
        return []
    # Fetch each policy via the MAD parser API.  This ensures that
    # Redis overrides and default policies are respected.  Use an
    # asynchronous HTTP client to avoid blocking the loop.
    policies: List[Dict[str, Any]] = []
    async with httpx.AsyncClient(timeout=5.0) as client:
        for name in depts:
            url = f"{MAD_PARSER}/rego_policy/{name}"
            try:
                resp = await client.get(url, headers={"accept": "application/json"})
            except Exception as exc:
                # Skip this policy on error
                continue
            if resp.status_code != 200:
                # Skip if not found or other error
                continue
            policy_text: Optional[str] = None
            try:
                data = resp.json()
                # Response should be a dict with a "policy" field
                if isinstance(data, dict):
                    policy_text = data.get("policy")
                # Fall back to raw JSON if not present
                if not policy_text and data:
                    # some endpoints may return plain string; guard
                    policy_text = data if isinstance(data, str) else None
            except Exception:
                # If JSON parsing fails, assume body is plain text
                policy_text = resp.text
            if policy_text and isinstance(policy_text, str):
                policies.append({"name": name, "policy": policy_text})
    return policies


# ---------------------------------------------------------------------------
# Orchestrator configuration proxy endpoints
#
# The action settings tab in the admin interface uses these routes to
# configure the orchestrator.  They simply forward GET and POST
# requests to the orchestrator's ``/config`` endpoint.  Any errors
# encountered when reaching the orchestrator are returned as HTTP
# errors to the caller.


@router.get("/config")
async def get_orchestrator_config() -> Any:
    """Proxy the GET /config request to the orchestrator.

    Returns the current configuration used by the orchestrator for
    decision blocking behaviour.  The response is returned as-is
    from the orchestrator.  Raises HTTPError when the orchestrator
    cannot be reached or does not return a 200 OK.
    """
    url = f"{ORCHESTRATOR}/config"
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(url, headers={"accept": "application/json"})
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Failed to reach orchestrator: {exc}")
    if resp.status_code != 200:
        raise HTTPException(status_code=resp.status_code, detail=resp.text)
    try:
        return resp.json()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to parse JSON from orchestrator: {exc}")


@router.post("/config")
async def set_orchestrator_config(body: Dict[str, Any]) -> Any:
    """Proxy the POST /config request to the orchestrator.

    The body should contain configuration fields accepted by the
    orchestrator (e.g. ``decision_block_level`` and
    ``allow_fallback_block``).  The response from the orchestrator is
    returned as-is on success.  A non-200 status from the orchestrator
    triggers an HTTPError to be raised.
    """
    url = f"{ORCHESTRATOR}/config"
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(
                url,
                json=body,
                headers={
                    "accept": "application/json",
                    "content-type": "application/json",
                },
            )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Failed to reach orchestrator: {exc}")
    # Accept 200, 201 or 204 as success codes
    if resp.status_code not in {200, 201, 204}:
        raise HTTPException(status_code=resp.status_code, detail=resp.text)
    # If the orchestrator returns a JSON body, forward it.  Otherwise
    # return an empty dict.  Use try/except to guard against JSON
    # parsing errors.
    try:
        if resp.content:
            return resp.json()
    except Exception:
        # treat non-JSON as success with no body
        pass
    return {}
